//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetBD.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Examan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Examan()
        {
            this.ExamRisques = new HashSet<ExamRisque>();
            this.TraductionExams = new HashSet<TraductionExam>();
        }
        [StringLength(30)]
        [DisplayName("Libelle de l'examen")]
        public string libelle { get; set; }

        [StringLength(30)]
        public string periodicite { get; set; }

        [StringLength(10)]
        [DisplayName("Numero de compte")]
        public string numCompte { get; set; }

        [RegularExpression(@"\d{1,2}(\.\d{1,2})?", ErrorMessage = "Le format doit être 99.99")]
        [DisplayName("Prix des travailleurs soumis")]
        public decimal prixSoumis { get; set; }

        [RegularExpression(@"\d{1,2}(\.\d{1,2})?", ErrorMessage = "Le format doit être 99.99")]
        [DisplayName("Prix des travailleurs non-soumis")]
        public decimal prixNonSoumis { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExamRisque> ExamRisques { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TraductionExam> TraductionExams { get; set; }
    }
}
