//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetBD.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class ExamRisque
    {
        [DisplayName("Libellé de l'examen")]
        public string E_E_libelle { get; set; }
        [DisplayName("Libellé du risque")]
        public string libelle { get; set; }

        [StringLength(100)]
        [DisplayName("Commentaire éventuel")]
        public string Commentaire { get; set; }
    
        public virtual Examan Examan { get; set; }
        public virtual Risque Risque { get; set; }
    }
}
