//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetBD.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBIG3A1Entities : DbContext
    {
        public DBIG3A1Entities()
            : base("name=DBIG3A1Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<Emploi> Emplois { get; set; }
        public virtual DbSet<Entreprise> Entreprises { get; set; }
        public virtual DbSet<Examan> Examen { get; set; }
        public virtual DbSet<ExamRisque> ExamRisques { get; set; }
        public virtual DbSet<Exposition> Expositions { get; set; }
        public virtual DbSet<Langue> Langues { get; set; }
        public virtual DbSet<Personne> Personnes { get; set; }
        public virtual DbSet<Profession> Professions { get; set; }
        public virtual DbSet<Risque> Risques { get; set; }
        public virtual DbSet<TraductionExam> TraductionExams { get; set; }
        public virtual DbSet<TraductionProf> TraductionProfs { get; set; }
        public virtual DbSet<TraductionRisque> TraductionRisques { get; set; }
    }
}
